services:
  genflow:
    image: genflow
    build:
      context: ..
      dockerfile: container/Dockerfile
    container_name: genflow-workflow
    volumes:
      - ..:/workspace/GenFlow:rw
      - ../Data:/workspace/GenFlow/Data:rw
      - ../results:/workspace/GenFlow/results:rw
      - ../logs:/workspace/GenFlow/logs:rw
      - ../Intermediate:/workspace/GenFlow/Intermediate:rw
    environment:
      SNAKEMAKE_THREADS: "8"
      SNAKEMAKE_CORES: "8"
      CONDA_PKGS_DIRS: /opt/conda/pkgs
      PYTHONUNBUFFERED: "1"
    working_dir: /workspace/GenFlow
    stdin_open: true
    tty: true
    networks:
      - genflow-network

networks:
  genflow-network:
    driver: bridge
